language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "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"
  local_dir: dist
  on:
    branch: main